asm c:vsnboot.asm,d:vsnboot.obj;
asm c:vsngo.asm,d:vsngo.obj;
asm c:vsncom.asm,d:vsncom.obj;
asm c:vsnmain.asm,d:vsnmain.obj;
asm c:vsnconfg.asm,d:vsnconfg.obj;
asm c:vsnldos.asm,d:vsnldos.obj;
asm c:vsnfrmt.asm,d:vsnfrmt.obj;
asm c:vsntnsfr.asm,d:vsntnsfr.obj;
asm c:vsnwss.asm,d:vsnwss.obj;
asm c:vsnbatch.asm,d:vsnbatch.obj;
asm c:vsnclock.asm,d:vsnclock.obj;
asm c:vsnprint.asm,d:vsnprint.obj;
asm c:vsnscrn.asm,d:vsnscrn.obj;
asm c:vsndisk.asm,d:vsndisk.obj;
asm c:vsnpict.asm,d:vsnpict.obj;
asm c:vsnerr.asm,d:vsnerr.obj;
asm c:vsnprmpt.asm,d:vsnprmpt.obj;
asm c:vsnvrfy.asm,d:vsnvrfy.obj;
asm c:vsnkey.asm,d:vsnkey.obj;
vsnlnknl

amcvnr.s,:serojamcvnrp.s,:spmtojamcvnryamdvnryojamcvne.s,:skyojvnnnmvrs:eomvr.,smomvradnyjacn.,syjvn