Pause Insert Bruce & James Program Publishers Inc. VSNDOS 2.0 # 1 in drive A:
dir a:
erase a:*.*
copy ..\src\vsnboot.asm a:
copy ..\src\vsnmain.asm a:
copy ..\src\vsnconfg.asm a:
copy ..\src\vsnldos.asm a:
copy ..\src\vsnfrmt.asm a:
copy vsnboot.exe a:

Pause Insert Bruce & James Program Publishers Inc. VSNDOS 2.0 # 2 in drive A:
dir a:
erase a:*.*
copy ..\src\vsngo.asm a:
copy ..\src\vsntnsfr.asm a:
copy ..\src\vsnwss.asm a:
copy ..\src\vsnbatch.asm a:
copy ..\src\vsnclock.asm a:
copy ..\src\vsnprint.asm a:
copy vsngo.com a:

Pause Insert Bruce & James Program Publishers Inc. VSNDOS 2.0 # 3 in drive A:
dir a:
erase a:*.*
copy ..\src\vsncom.asm a:
copy ..\src\vsnscrn.asm a:
copy ..\src\vsndisk.asm a:
copy ..\src\vsnpict.asm a:
copy ..\src\vsnerr.asm a:
copy vsnmain.com a:
copy vsncom.com a:

Pause Insert Bruce & James Program Publishers Inc. VSNDOS 2.0 # 4 in drive A:
dir a:
erase a:*.*
copy ..\src\vsnprmpt.asm a:
copy ..\src\vsnvrfy.asm a:
copy ..\src\vsnkey.asm a:

copy vsnbak.bat a:
copy vsnlnk.bat a:
copy vsnlnknl.bat a:
copy vsnlink.lnk a:
copy vsnsys.bat a:
copy vsnsysnl.bat a:
 l.bat a:
 sbkbta cp :slkbta cp :slklbta cp :sln.n :s

        n     Cuezn
os  n
    n   uz
s 
    zs
  s ss  ,   las_u     o b    