masm ..\src\vsnboot.asm    ..\obj\vsnboot.obj;
masm ..\src\vsngo.asm      ..\obj\vsngo.obj;
masm ..\src\vsncom.asm     ..\obj\vsncom.obj;
masm ..\src\vsnmain.asm    ..\obj\vsnmain.obj;
masm ..\src\vsnconfg.asm   ..\obj\vsnconfg.obj;
masm ..\src\vsnldos.asm    ..\obj\vsnldos.obj;
masm ..\src\vsnfrmt.asm    ..\obj\vsnfrmt.obj;
masm ..\src\vsntnsfr.asm   ..\obj\vsntnsfr.obj;
masm ..\src\vsnwss.asm     ..\obj\vsnwss.obj;
masm ..\src\vsnbatch.asm   ..\obj\vsnbatch.obj;
masm ..\src\vsnclock.asm   ..\obj\vsnclock.obj;
masm ..\src\vsnprint.asm   ..\obj\vsnprint.obj;
masm ..\src\vsnscrn.asm    ..\obj\vsnscrn.obj;
masm ..\src\vsndisk.asm    ..\obj\vsndisk.obj;
masm ..\src\vsnpict.asm    ..\obj\vsnpict.obj;
masm ..\src\vsnerr.asm     ..\obj\vsnerr.obj;
masm ..\src\vsnprmpt.asm   ..\obj\vsnprmpt.obj;
masm ..\src\vsnvrfy.asm    ..\obj\vsnvrfy.obj;
masm ..\src\vsnkey.asm     ..\obj\vsnkey.obj;
vsnlnknl

                                                                                                   