masm ..\src\vsnboot.asm    ..\obj\vsnboot.obj    lpt1:;
masm ..\src\vsngo.asm      ..\obj\vsngo.obj      lpt1:;
masm ..\src\vsncom.asm     ..\obj\vsncom.obj     lpt1:;
masm ..\src\vsnmain.asm    ..\obj\vsnmain.obj    lpt1:;
masm ..\src\vsnconfg.asm   ..\obj\vsnconfg.obj   lpt1:;
masm ..\src\vsnldos.asm    ..\obj\vsnldos.obj    lpt1:;
masm ..\src\vsnfrmt.asm    ..\obj\vsnfrmt.obj    lpt1:;
masm ..\src\vsntnsfr.asm   ..\obj\vsntnsfr.obj   lpt1:;
masm ..\src\vsnwss.asm     ..\obj\vsnwss.obj     lpt1:;
masm ..\src\vsnbatch.asm   ..\obj\vsnbatch.obj   lpt1:;
masm ..\src\vsnclock.asm   ..\obj\vsnclock.obj   lpt1:;
masm ..\src\vsnprint.asm   ..\obj\vsnprint.obj   lpt1:;
masm ..\src\vsnscrn.asm    ..\obj\vsnscrn.obj    lpt1:;
masm ..\src\vsndisk.asm    ..\obj\vsndisk.obj    lpt1:;
masm ..\src\vsnpict.asm    ..\obj\vsnpict.obj    lpt1:;
masm ..\src\vsnerr.asm     ..\obj\vsnerr.obj     lpt1:;
masm ..\src\vsnprmpt.asm   ..\obj\vsnprmpt.obj   lpt1:;
masm ..\src\vsnvrfy.asm    ..\obj\vsnvrfy.obj    lpt1:;
masm ..\src\vsnkey.asm     ..\obj\vsnkey.obj     lpt1:;
vsnlnk
                                                                                                                                                                                            