Pause Insert Bruce & James Program Publishers Inc. VSNDOS 2.0 # 1 in drive A:
dir a:
erase a:*.*
copy c:vsnboot.asm a:
copy c:vsnmain.asm a:
copy c:vsnconfg.asm a:
copy c:vsnldos.asm a:
copy c:vsnfrmt.asm a:
copy b:vsnboot.exe a:

Pause Insert Bruce & James Program Publishers Inc. VSNDOS 2.0 # 2 in drive A:
dir a:
erase a:*.*
copy c:vsngo.asm a:
copy c:vsntnsfr.asm a:
copy c:vsnwss.asm a:
copy c:vsnbatch.asm a:
copy c:vsnclock.asm a:
copy c:vsnprint.asm a:
copy b:vsngo.com a:

Pause Insert Bruce & James Program Publishers Inc. VSNDOS 2.0 # 3 in drive A:
dir a:
erase a:*.*
copy c:vsncom.asm a:
copy c:vsnscrn.asm a:
copy c:vsndisk.asm a:
copy c:vsnpict.asm a:
copy c:vsnerr.asm a:
copy b:vsnmain.com a:
copy b:vsncom.com a:

Pause Insert Bruce & James Program Publishers Inc. VSNDOS 2.0 # 4 in drive A:
dir a:
erase a:*.*
copy c:vsnprmpt.asm a:
copy c:vsnvrfy.asm a:
copy c:vsnkey.asm a:

copy b:vsnbak.bat a:
copy b:vsnlnk.bat a:
copy b:vsnlnknl.bat a:
copy b:vsnlink.lnk a:
copy b:vsnsys.bat a:
copy b:vsnsysnl.bat a:

oybvny.a :
oybvnyn.a :

yvya:obnna:
vaona
an
nnoycvnrp.s :
oycvnryamacp :skyamacp :sbkbtacp :slkbtacp :slklbtacp :sln.n :s

        n    Cuezn
os  n
    n  uz
s 
   zs
 s ss  ,  las_u    o b   