basic settab
asm c:vsnboot.asm,d:vsnboot.obj,lpt1:;
asm c:vsngo.asm,d:vsngo.obj,lpt1:;
asm c:vsncom.asm,d:vsncom.obj,lpt1:;
asm c:vsnmain.asm,d:vsnmain.obj,lpt1:;
asm c:vsnconfg.asm,d:vsnconfg.obj,lpt1:;
asm c:vsnldos.asm,d:vsnldos.obj,lpt1:;
asm c:vsnfrmt.asm,d:vsnfrmt.obj,lpt1:;
asm c:vsntnsfr.asm,d:vsntnsfr.obj,lpt1:;
asm c:vsnwss.asm,d:vsnwss.obj,lpt1:;
asm c:vsnbatch.asm,d:vsnbatch.obj,lpt1:;
asm c:vsnclock.asm,d:vsnclock.obj,lpt1:;
asm c:vsnprint.asm,d:vsnprint.obj,lpt1:;
asm c:vsnscrn.asm,d:vsnscrn.obj,lpt1:;
asm c:vsndisk.asm,d:vsndisk.obj,lpt1:;
asm c:vsnpict.asm,d:vsnpict.obj,lpt1:;
asm c:vsnerr.asm,d:vsnerr.obj,lpt1:;
asm c:vsnprmpt.asm,d:vsnprmpt.obj,lpt1:;
asm c:vsnvrfy.asm,d:vsnvrfy.obj,lpt1:;
asm c:vsnkey.asm,d:vsnkey.obj,lpt1:;
vsnlnk

t:vnn:vn:n::ikamdvnikojlt:amcvnitamdvnitojlt:amcvnr.s,:serojlt:amcvnrp.s,:spmtojlt:amcvnryamdvnryojlt:amcvne.s,:skyojlta_4        b   b,ffh
       jc   ocryncsay

       dc   x

    ocryncsay        o   fl_iehg,x
       mv   